force-app/main/default/objects/Stock_Count__c/Stock_Count__c.object-meta.xml
<CustomObject>
    <description>Stock counting object</description>
    <label>Stock Count</label>
    <nameField>
        <label>Stock Count Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks Count</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Count__c/fields/Stock_Count_Number__c.field-meta.xml
<CustomField>
    <fullName>Stock_Count_Number__c</fullName>
    <description>Stock count value</description>
    <label>Stock Count</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StockCountDomain.cls
public with sharing class StockCountDomain {
  /**
   * updates selected stock count record count with the value difference
   * @param {Stock_Count__c} record
   * @param {Decimal} value
   * @return {Stock_Count__c}
   */
  public static Stock_Count__c UpdateStockCountValue(
    Stock_Count__c record,
    Decimal value
  ) {
    if (value != null && value >= 0 && value < record.Stock_Count_Number__c) {
      record.Stock_Count_Number__c = record.Stock_Count_Number__c - value;
    }
    return record;
  }
}