force-app/main/default/objects/Stock_Count__c/Stock_Count__c.object-meta.xml
<CustomObject>
    <description>Stock counting object</description>
    <label>Stock Count</label>
    <nameField>
        <label>Stock Count Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks Count</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Count__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product id</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks Count</relationshipLabel>
    <relationshipName>Stocks_Count</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Count__c/fields/Stock_Count_Number__c.field-meta.xml
<CustomField>
    <fullName>Stock_Count_Number__c</fullName>
    <description>Stock count value</description>
    <label>Stock Count</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StockCountSelector.cls
public with sharing class StockCountSelector {
  /**
   * queries stock counts for specific product records
   * @param {Set<Id>}productIds
   * @return {List<Stock_Count__c>}
   */
  public static List<Stock_Count__c> GetRecords(Set<Id> productIds) {
    return [
      SELECT Id, Stock_Count_Number__c, Product_Id__c
      FROM Stock_Count__c
      WHERE Product_Id__c IN :productIds
      WITH SECURITY_ENFORCED
      FOR UPDATE
    ];
  }
}